// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckApps(): Promise<{ [key: string]: boolean }>;

export function GetDevices(): Promise<Array<main.DeviceInfo>>;

export function InstallNrfr(): Promise<void>;

export function InstallShizuku(): Promise<void>;

export function SelectDevice(arg1: string): Promise<void>;

export function StartNrfr(): Promise<void>;

export function StartShizuku(): Promise<void>;

export function WindowClose(): Promise<void>;

export function WindowMaximise(): Promise<void>;

export function WindowMinimise(): Promise<void>;
